import { defineConfig } from "drizzle-kit"

/**
 * Drizzle config for the per-challenge SQLite database (`<challenge>/.omp/state.db`).
 *
 * Spec: `.omc/specs/deep-interview-database-mcp.md`.
 *
 * - Dialect: SQLite (WAL mode, per-challenge file).
 * - Driver: bun:sqlite (native, embedded — no separate process needed for
 *   schema generation; runtime open lives in `src/db/index.ts` once that file
 *   exists in T2).
 * - Schema: `src/db/schema.ts` — 10 tables (state + 4 state array FK +
 *   candidates + 4 candidates array FK).
 * - Output: `src/db/migrations/` — SQL files generated by `drizzle-kit generate`.
 *
 * Migration runner setup (T2) wires `drizzle-kit migrate` against the
 * per-challenge `state.db` at runtime via `migrate()` from
 * `drizzle-orm/bun-sqlite/migrator`.
 */
export default defineConfig({
  schema: "./src/db/schema.ts",
  out: "./src/db/migrations",
  dialect: "sqlite",
})
