/**
 * DB connection helper for the global SQLite database (`<repo-root>/state.db`).
 *
 * Spec: `.omc/specs/deep-interview-database-mcp.md` (T2 — Drizzle migration
 * runner + connection helper).
 *
 * Fresh start (사용자 결정 2026-05-30): 기존 `state.json` + `candidates/*.json`
 * 활용 안 함. 새 DB 시스템 가동 시점 = 빈 `state.db` 에 Drizzle migrate 호출 →
 * 10 table + composite FK + cascade DDL 자동 생성.
 *
 * Lifecycle (T2 결정): 모듈 함수만 제공 — 호출자가 lifecycle 결정.
 *   - T3 (migration script): 폐기 (fresh start 라 변환 작업 없음)
 *   - T4 (DB MCP server): process 안 lazy singleton 으로 사용 예정
 *   - Plugin 안 `omp_load_challenge` 등의 DB 통합: 별도 task
 *
 * Re-exports `./schema` 로 호출자가 typed query (`db.query.candidates.findFirst({
 * with: { combinedFrom: true, ... } })`) 직접 사용 가능.
 */

import { Database } from "bun:sqlite"
import { drizzle, type BunSQLiteDatabase } from "drizzle-orm/bun-sqlite"
import { migrate } from "drizzle-orm/bun-sqlite/migrator"
import { fileURLToPath } from "node:url"
import { dirname, resolve } from "node:path"

import * as schema from "./schema"

export * from "./schema"

/** Drizzle DB type alias with full schema relations available. */
export type OmpDatabase = BunSQLiteDatabase<typeof schema>

/**
 * Resolve the migrations directory path. Drizzle expects an absolute path to
 * the folder containing `0000_*.sql` + `meta/` (generated by `drizzle-kit
 * generate`). Computed relative to this module so it works from any CWD.
 */
function defaultMigrationsFolder(): string {
  const here = dirname(fileURLToPath(import.meta.url))
  return resolve(here, "migrations")
}

/**
 * Options for `openDb()`. All optional except `dbPath`.
 *
 * - `dbPath`: absolute path to the SQLite file (e.g.
 *   `<repo-root>/state.db`). Caller responsibility — this helper does not
 *   hardcode the location.
 * - `migrationsFolder`: override the migrations folder. Defaults to
 *   `src/db/migrations` resolved relative to this module.
 * - `runMigrations`: if `true` (default), runs `migrate()` after open. Set
 *   `false` for tests that want to verify the open path without applying
 *   schema (rare — most callers want migrations applied).
 * - `applyPragmas`: if `true` (default), sets `journal_mode = WAL` and
 *   `foreign_keys = ON`. Set `false` only when caller wants explicit control
 *   (rare).
 */
export interface OpenDbOptions {
  dbPath: string
  migrationsFolder?: string
  runMigrations?: boolean
  applyPragmas?: boolean
}

/**
 * Open a SQLite database at `dbPath`, apply standard pragmas (WAL +
 * foreign_keys), and run Drizzle migrations to current schema. Returns a
 * Drizzle DB instance configured with the full schema (relations available).
 *
 * Idempotent: calling `migrate()` on a DB that is already at the latest
 * schema is a noop (Drizzle tracks applied migrations in
 * `__drizzle_migrations` table).
 *
 * The caller owns lifecycle (no module-level singleton here — different
 * processes / tests want different lifetimes). To close, call
 * `closeDb(db)` or access the underlying `bun:sqlite` Database via
 * `(db as any).$client.close()`.
 */
export function openDb(options: OpenDbOptions): OmpDatabase {
  const {
    dbPath,
    migrationsFolder = defaultMigrationsFolder(),
    runMigrations = true,
    applyPragmas = true,
  } = options

  const sqlite = new Database(dbPath)

  if (applyPragmas) {
    // WAL mode = reader-many writer-one. Required for the spec's "외부 read
    // 채널" guarantee (sqlite3 -readonly while MCP server is writing).
    sqlite.exec("PRAGMA journal_mode = WAL;")
    // Composite FK + cascade DDL only enforced when this is ON. SQLite default
    // is OFF (historical compat) — must opt-in per connection.
    sqlite.exec("PRAGMA foreign_keys = ON;")
  }

  const db = drizzle(sqlite, { schema })

  if (runMigrations) {
    migrate(db, { migrationsFolder })
  }

  return db
}

/**
 * Close the underlying `bun:sqlite` Database. Drizzle does not expose a
 * public close API; we reach the underlying client via the documented
 * `$client` field.
 */
export function closeDb(db: OmpDatabase): void {
  // Drizzle stores the bun:sqlite Database on `$client`. Type system does not
  // expose it cleanly — narrow via cast at this single seam.
  const sqlite = (db as unknown as { $client: Database }).$client
  sqlite.close()
}
