/**
 * Append-only writer for the per-challenge `journal.md`.
 *
 * `journal.md` is OmP's progress-visibility surface. Its contract:
 *
 * - **Append-only.** New content is *only* appended; nothing in this module
 *   ever seeks, rewrites, or parses existing content.
 * - **Human-read-only.** Humans read it to understand what OmP is thinking;
 *   they never edit it. Corrections flow through the prompt, and the
 *   Orchestrator applies them via {@link appendUserCorrection} (plus a
 *   mutation to `state.json`).
 * - **Continuous.** The T19 writer hook fires after every agent message and
 *   should always call into this module so a human tailing the file sees
 *   progress in near real-time, not a flush-at-the-end dump.
 *
 * The detailed hook wiring lives in T19; this module is the file-I/O primitive
 * it will stand on.
 */

import { appendFileSync, existsSync, mkdirSync, writeFileSync } from "node:fs"
import { dirname } from "node:path"
import { resolveJournalPath } from "./layout"
import type { ChallengeState, UserCorrection } from "./challenge-state"

function ensureParentDir(filePath: string): void {
  mkdirSync(dirname(filePath), { recursive: true })
}

/**
 * Write the journal header on a fresh challenge, iff the file does not yet
 * exist. No-op on existing journals (append-only contract). Defensively
 * ensures the `.omp/` directory exists so this can be called safely without
 * having run {@link import("./io").initializeOmpDir} first.
 */
export function initializeJournal(
  challengeDir: string,
  state: ChallengeState,
  now: Date = new Date(),
): void {
  const journalPath = resolveJournalPath(challengeDir)
  ensureParentDir(journalPath)
  if (existsSync(journalPath)) {
    return
  }
  const header = buildInitialJournal(state, now)
  writeFileSync(journalPath, header, "utf-8")
}

/**
 * Append a single `## {heading}` section to the journal.
 *
 * The heading is automatically timestamped so the human can scan the file
 * and know when each entry landed. Body is written verbatim (no escaping);
 * callers are expected to pass clean markdown. Callers may pass either a
 * `Date` (default: `new Date()`) or a pre-formatted ISO-8601 string — the
 * latter is what {@link appendUserCorrection} uses to preserve the exact
 * timestamp string that was stored in `state.json` without round-tripping
 * through `Date` and losing sub-millisecond precision.
 *
 * Defensively ensures the `.omp/` directory exists.
 */
export function appendJournalSection(
  challengeDir: string,
  heading: string,
  body: string,
  when: Date | string = new Date(),
): void {
  const journalPath = resolveJournalPath(challengeDir)
  ensureParentDir(journalPath)
  const timestamp = typeof when === "string" ? when : when.toISOString()
  const section = formatSection(heading, body, timestamp)
  appendFileSync(journalPath, section, "utf-8")
}

/**
 * Convenience wrapper for the prompt-driven correction protocol (T20).
 *
 * Orchestrator should call this immediately after mutating `state.json` so the
 * journal reflects exactly what changed and why, with the original user text
 * preserved verbatim for audit. The `correction.timestamp` string is passed
 * through verbatim (it has already been Zod-validated as ISO-8601 by
 * `UserCorrectionSchema`), so no `Date` round-trip happens here.
 */
export function appendUserCorrection(
  challengeDir: string,
  correction: UserCorrection,
): void {
  const body = [
    correction.applied_delta ? `**Applied delta:** ${correction.applied_delta}` : null,
    "",
    "**User said (verbatim):**",
    "",
    quoteBlock(correction.user_text),
  ]
    .filter((line): line is string => line !== null)
    .join("\n")
  appendJournalSection(challengeDir, "User correction", body, correction.timestamp)
}

function formatSection(heading: string, body: string, timestamp: string): string {
  const trimmedBody = body.replace(/\s+$/u, "")
  return `\n## ${heading} — ${timestamp}\n\n${trimmedBody}\n`
}

function buildInitialJournal(state: ChallengeState, now: Date): string {
  const lines = [
    "# oh-my-pwn Handoff Journal",
    "",
    `_Challenge dir: \`${state.challenge_dir}\`_  `,
    `_Created: ${now.toISOString()}_`,
    "",
    "> This file is an **append-only progress log** written by OmP agents.",
    "> It is **read-only for humans** — corrections flow through the prompt",
    "> channel and are applied by the Orchestrator to `state.json` plus a",
    "> `## User correction` block below. Do not edit this file by hand.",
    "",
    "## Inputs",
    "",
    `- binary (input): \`${state.binary_input_path ?? "(unset)"}\``,
    `- Dockerfile: \`${state.dockerfile_path}\``,
    `- source present: ${state.source_present}`,
    "",
  ]
  return lines.join("\n")
}

function quoteBlock(text: string): string {
  return text
    .split(/\r?\n/u)
    .map((line) => `> ${line}`)
    .join("\n")
}
